### ISSUE TITLE
Subir el IEEE830

### ISSUE THREAD

**Issue by danielasgomez273** [danielasgomez273/a36g36#1]
Consigna: Registrar la Especificación de Requerimientos mediante la documentación IEEE830 (subirlo en una carpeta de GitHub en la rama main).

**Comment by danielasgomez273** [comment]
@DHerrera85 no se visualiza el doc, probablemente por el formato. 
Podrás revisarlo? Quizás si lo subís en formato PDF?

**Comment by DHerrera85** [comment]
Se sube archivo en Pdf

**Comment by danielasgomez273** [comment]
Se desconfiguró el índice ! 



![Image](https://user-images.githubusercontent.com/91642474/193936182-87322cd4-fc9c-4313-8645-7aadcf8daa52.png)

**Comment by DHerrera85** [comment]
Se sube archivo pdf con índice configurado
