### ISSUE TITLE
Cargar la US del prestador de salud

### ISSUE THREAD

**Issue by danielasgomez273** [danielasgomez273/a36g36#4]
- US desde las 9 hasta la 17
- Respetar el formato del IEEE830

**Comment by DHerrera85** [comment]
**Como** prestador de salud  
**quiero** ver estadísticas de los usuarios de la aplicación 
**para** ofrecer paquetes de servicios médicos personalizados

**Comment by danielasgomez273** [comment]
@DHerrera85 esto va cargado en una issue nueva. 
La issue "Cargar la US del prestador de salud" está asignada a Maxi, a mí y a vos. 

Se trata de la tarea de cargar las US desde la 9 hasta la  17.

**Comment by DHerrera85** [comment]
Se carga US#12 correspondiente

**Comment by danielasgomez273** [comment]
Asignadas a Project / Milestone
